// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.IncomeTaxCalculator
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("year")]
        public long Year { get; set; }

        [JsonProperty("filing_status")]
        public string FilingStatus { get; set; }

        [JsonProperty("income")]
        public long Income { get; set; }

        [JsonProperty("standardDeduction")]
        public long StandardDeduction { get; set; }

        [JsonProperty("taxableIncome")]
        public long TaxableIncome { get; set; }

        [JsonProperty("totalTax")]
        public double TotalTax { get; set; }

        [JsonProperty("effectiveRate")]
        public string EffectiveRate { get; set; }

        [JsonProperty("marginalRate")]
        public string MarginalRate { get; set; }

        [JsonProperty("incomeAfterTax")]
        public double IncomeAfterTax { get; set; }

        [JsonProperty("brackets")]
        public Bracket[] Brackets { get; set; }
    }

    public partial class Bracket
    {
        [JsonProperty("rate")]
        public double Rate { get; set; }

        [JsonProperty("ratePercent")]
        public string RatePercent { get; set; }

        [JsonProperty("rangeMin")]
        public long RangeMin { get; set; }

        [JsonProperty("rangeMax")]
        public long RangeMax { get; set; }

        [JsonProperty("taxableAmount")]
        public long TaxableAmount { get; set; }

        [JsonProperty("taxAmount")]
        public double TaxAmount { get; set; }
    }
}
